-- ============================================================
-- Supabase Database Schema for Face Recognition Attendance
-- 
-- This SQL creates the attendance table structure.
-- Copy and paste this into Supabase SQL Editor and run it.
-- ============================================================

-- Create attendance table
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  
  -- Student information
  name TEXT NOT NULL,
  roll_no TEXT NOT NULL,
  department TEXT,
  
  -- Timestamps
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_attendance_roll_no 
ON attendance(roll_no);

CREATE INDEX IF NOT EXISTS idx_attendance_timestamp 
ON attendance(timestamp);

CREATE INDEX IF NOT EXISTS idx_attendance_date 
ON attendance(DATE(timestamp));

-- Add comment
COMMENT ON TABLE attendance IS 'Stores attendance logs for face recognition system';
COMMENT ON COLUMN attendance.name IS 'Student name';
COMMENT ON COLUMN attendance.roll_no IS 'Student roll number (unique ID)';
COMMENT ON COLUMN attendance.department IS 'Student section or department';
COMMENT ON COLUMN attendance.timestamp IS 'When attendance was logged';
COMMENT ON COLUMN attendance.created_at IS 'Server-side creation timestamp';

-- Optional: Enable RLS for production
-- ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;

-- Optional: Add sample data (remove after testing)
-- INSERT INTO attendance (name, roll_no, department, timestamp) VALUES
-- ('Arjun Sharma', 'CSE001', 'A2', NOW()),
-- ('Priya Singh', 'CSE002', 'B1', NOW());
